services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            internal_net:
                ipv4_address: 192.168.54.10 # IP fija dentro del rango de la subred
        volumes:
            - ./env-files/.env:/var/www/html/.env
            - ./la-diera:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        ports:
            - '8080:80' # Mapea el puerto 80 del contenedor al puerto 8080 del host

networks:
    internal_net:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.54.0/24
